import type { Metadata } from "next";
import { Geist, Geist_Mono } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./lib/auth-context";
import {UserProvider} from "./lib/UserContext";
import { Orbitron, Assistant } from "next/font/google";

const orbitron = Orbitron({ subsets: ["latin"], weight: ["500", "700"] });
const assistant = Assistant({ subsets: ["latin"], weight: ["400", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="he" >
            <body className={` ${assistant.className}`}>
                <UserProvider>
                    <Navbar />
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
